### ISSUE TITLE
Error calling method AgentLifeCycleListener.buildStarted for listener com.browserstack.automate.ci.teamcity.BrowserStackLocalAgent: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by vbedrosova** [browserstack/teamcity-plugin#20]
For version 2.0.0 I observe multiple exceptions in teamcity-agent.log

```
[2019-10-29 17:15:28,779]   WARN - ildServer.util.EventDispatcher - Error in event handler: Error calling method AgentLifeCycleListener.buildStarted for listener com.browserstack.automate.ci.teamcity.BrowserStackLocalAgent: java.util.NoSuchElementException
Error calling method AgentLifeCycleListener.buildStarted for listener com.browserstack.automate.ci.teamcity.BrowserStackLocalAgent: java.util.NoSuchElementException
	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:151)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:125)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:75)
	at com.sun.proxy.$Proxy7.buildStarted(Unknown Source)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.FireBuildStartedStage.doBuildState(FireBuildStartedStage.java:20)
	at jetbrains.buildServer.agent.impl.buildStages.startStages.FireEventStageBase.doBuildStage(FireEventStageBase.java:26)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:31)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor$1.callStage(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.callRunStage(StagesExecutor.java:76)
	at jetbrains.buildServer.agent.impl.buildStages.StagesExecutor.doStages(StagesExecutor.java:35)
	at jetbrains.buildServer.agent.impl.buildStages.BuildStagesExecutor.doStages(BuildStagesExecutor.java:24)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.doStages(BuildRunActionImpl.java:79)
	at jetbrains.buildServer.agent.impl.BuildRunActionImpl.runBuild(BuildRunActionImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.doActualBuild(BuildAgentImpl.java:312)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.access$100(BuildAgentImpl.java:55)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl$1.run(BuildAgentImpl.java:275)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException
	at java.util.ArrayList$Itr.next(ArrayList.java:862)
	at com.browserstack.automate.ci.teamcity.BrowserStackLocalAgent.buildStarted(BrowserStackLocalAgent.java:221)
	at sun.reflect.GeneratedMethodAccessor66.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.util.EventDispatcher$3.run(EventDispatcher.java:131)
	... 17 more
```

**Comment by RohanImmanuel** [comment]
This has been fixed here: https://github.com/browserstack/teamcity-plugin/pull/21

Closing this Issue
